#!/bin/bash
# Copyright (c) 2009 Cloudera, inc
#
# Performs a release build

set -e

if [ $(uname -s) = "SunOS" ]; then
if [ $(isainfo -b) != "64" -a -z "$SKIP_EXTRA_NATIVE" ]; then
  echo Release build should be done on a 64-bit box to generate 1>&2
  echo both 64 and 32 bit native libraries. 1>&2
  exit 1
fi
else
if [ $(uname -m) != "x86_64" -a -z "$SKIP_EXTRA_NATIVE" ]; then
  echo Release build should be done on a 64-bit box to generate 1>&2
  echo both 64 and 32 bit native libraries. 1>&2
  exit 1
fi
fi

JAVA32_HOME=${JAVA32_HOME:-$JAVA_HOME}
JAVA64_HOME=${JAVA64_HOME:-$JAVA_HOME}

# Do the build
BIN_DIR=$(readlink -f $(dirname $0))
RELEASE_DIR=$BIN_DIR/..

cd $RELEASE_DIR

if [ -z "$SKIP_EXTRA_NATIVE" ]; then
JAVA_HOME=$JAVA32_HOME \
  CFLAGS=-m32 \
  CXXFLAGS=-m32 \
  ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Dlibhdfs=true \
  -Dcompile.native=true \
  -Dfusedfs=true \
  -Dcompile.c++=true \
  -Dforrest.home=$FORREST_HOME \
  -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
  -propertyfile cloudera/build.properties \
  clean task-controller package-native

JAVA_HOME=$JAVA64_HOME
fi

if [ -z "$SKIP_JDIFF" ]; then
ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Djdiff.stable=0.20.1 \
  -Djdiff.build.dir=build/docs/jdiff-cloudera \
  -propertyfile build.properties \
  -propertyfile cloudera/build.properties api-report
fi

# Copy them into the main build directory to be included in the tarball
mkdir -p build/hadoop-$FULL_VERSION/docs/

ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Dlibhdfs=true \
  -Dcompile.native=true \
  -Dfusedfs=true \
  -Dcompile.c++=true \
  -Dforrest.home=$FORREST_HOME \
  -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
  -propertyfile cloudera/build.properties \
  compile-core-native compile-c++ compile-c++-examples task-controller tar

if [ -z "$SKIP_MVN_EXPLICIT" ]; then
# Change to cloudera/maven directory, and install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
cd $BIN_DIR/maven-packaging
mvn -Dnot.cdh.release.build=false install $DO_MAVEN_DEPLOY
fi
